### ISSUE TITLE
User can create profile name

### ISSUE THREAD

**Issue by eniolajohnson** [eniolajohnson/ajax-project#2]
Feature
User can create a profile name.

## 💰 Motivation

Users like to personalize things! 😄

## 📐 Plan

Create an input field for users to enter their profile details into and save their data to local storage.

## 🖼️ Wireframe

https://www.figma.com/file/4I7X4tSK0zJnbzbCKcxad8/Quizlee?node-id=2%3A5

## ✅ Task List

- [ ] Pick a nice font pair from Google Fonts for headings and body text.
- [ ] Pick a nice accent color.
- [ ] Create a simple, polished form in the HTML and CSS that shows a placeholder name for the user.
- [ ] Apply fonts to the heading, labels, and form input.
- [ ] Check to make sure that the page looks good on mobile and desktop.
- [ ] Make form input `required`.
- [ ] Make the `name` attribute of the form input element match the key of the profile data model.
- [ ] Listen for `'submit'` event on the form.
- [ ] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [ ] Test all functionality again.
